workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "web"

stages:
  - 00-initialization
  - 01-test-initial-state
  - 02-test-solution
  - 03-cleanup
  - 04-publish

default:
  image: "pingdevops.com/ci-utils/docker-builds-runner:edb6f37cedb342138aca215a69474e679b55390d5150ce8400eac264f2a864ae"
  services:
    - name: "docker:18.09-dind"
  tags:
    - k8s

variables:
  DOCKER_HOST: "tcp://localhost:2375"
  DOCKER_API_VERSION: "1.39"
  KUBERNETES_CPU_REQUEST: "1250m"
  KUBERNETES_CPU_LIMIT: "2000m"
  KUBERNETES_MEMORY_REQUEST: "500Mi"
  KUBERNETES_MEMORY_LIMIT: "500Mi"
  KUBERNETES_POLL_TIMEOUT: 600

initialization:
  stage: 00-initialization
  script:
    - "./.gitlab-ci/00-initialization.sh"

test-initial-state:
   stage: 01-test-initial-state
   script:
    - "./.gitlab-ci/01-test-initial-state.sh"

postman_tests:
    stage: 02-test-solution
    image:
      name: postman/neman_alpine33
      entrypoint: [""]
    script:
      - newman --version
      - newman run solutions_postman_collection.json

cleanup:
  stage: 03-cleanup
  when: always
  script:
    - "./.gitlab-ci/03-cleanup.sh"

publish:
  stage: 04-publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+\-\d{8}\-\d{2}$/
  script:
    - "./.gitlab-ci/04-publish.sh"